### ISSUE TITLE
It tries to open files that do not exist in a HDD's root directory

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/udfs#2]
Such as desktop.ini/autorun.inf. How can that be changed?

**Comment by Alter-1** [comment]
All this staff is handled by OS, event UI, FS driver handles them in regular way, like all other files.

**Comment by Alter-1** [comment]
So, you cannot change it. You can try to disable autorun in your OS

**Comment by Zero3K** [comment]
Okay.
