### ISSUE TITLE
How can one fix the following asserts?

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/udfs#3]
*** Assertion failed: !(check_size & (2048-1))
***   Source File: ../drivers/filesystems/udfs/udf_info/extent.cpp, line 2778

*** Assertion failed: FALSE
***   Source File: ../drivers/filesystems/udfs/Include/wcache_lib.cpp, line 2534

*** Assertion failed: FALSE
***   Source File: ../drivers/filesystems/udfs/udf_info/alloc.cpp, line 847

*** Assertion failed: block_type & WCACHE_BLOCK_USED
***   Source File: ../drivers/filesystems/udfs/Include/wcache_lib.cpp, line 3058

*** Assertion failed: !PartNum
***   Source File: ../drivers/filesystems/udfs/udf_info/udf_info.cpp, line 988

*** Assertion failed: i <= SearchLim
***   Source File: ../drivers/filesystems/udfs/udf_info/alloc.cpp, line 601

*** Assertion failed: PartNum < 3
***   Source File: ../drivers/filesystems/udfs/udf_info/extent.cpp, line 2257

*** Assertion failed: OS_SUCCESS(status)
***   Source File: ../drivers/filesystems/udfs/Include/phys_lib.cpp, line 4042

*** Assertion failed: FileInfo->Dloc->FELoc.Mapping[0].extLocation
***   Source File: ../drivers/filesystems/udfs/udf_info/udf_info.cpp, line 4131

*** Assertion failed: lba
***   Source File: ../drivers/filesystems/udfs/udf_info/udf_info.cpp, line 3974

**Comment by Alter-1** [comment]
each one means that smth goes wrong. *really* wrong
Each one is subject to study code and debug. I have no time for this.

Please, check if code is compiled with #pragma pack 8 by default.
And may be it worth to compare with original code from my site. It's may be smth. was modified when porting to ROS build environment.

**Comment by Zero3K** [comment]
The guy I found will eventually fix all of the asserts (he has fixed some already).
